FIND_PATH(LIBCXX_VECTOR vector /usr/include/c++/v1 /usr/local/include/c++/v1)

SET(HAS_LIBCXX False)
MESSAGE(STATUS "LIBCXX_VECTOR:" ${LIBCXX_VECTOR})
IF(NOT(${LIBCXX_VECTOR} MATCHES "NOTFOUND"))
  SET(HAS_LIBCXX True)
ENDIF(NOT(${LIBCXX_VECTOR} MATCHES "NOTFOUND"))
