SET(CLANG_NAME "[Cc]lang")
SET(HAS_CLANG False)
IF(${CMAKE_CXX_COMPILER_ID} MATCHES ${CLANG_NAME} OR ${CMAKE_CXX_COMPILER} MATCHES ${CLANG_NAME})
  SET(HAS_CLANG True)
ENDIF(${CMAKE_CXX_COMPILER_ID} MATCHES ${CLANG_NAME} OR ${CMAKE_CXX_COMPILER} MATCHES ${CLANG_NAME})

